server:
  port: 80


spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    username: root
    password: 542270191MSzyl
    url: jdbc:mysql://47.108.63.126:3306/netease?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 40000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: selcet 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true